# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8ec3974344941789fe8aaef0d7d547e48b9c707bd3d049a7f5393359f840d757ab9e268876c83320a00dd0869f5745f895294fde6d314bb8e52ef9416f9545c9

test:
  secret_key_base: 327d779d9bc6fff90695414483c1bb64f3611e2a2c52d714de048053f9591a9fbc1b71f740d3f6e29f33008a7f05adc26dc6a671bd44a6dbc64d39f513a9a8fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
